# I included this because I couldn't find a corresponding API endpoint

CLASSIC = "CLASSIC"
ODIN = "ODIN"
ARAM = "ARAM"
TUTORIAL = "TUTORIAL"
ONEFORALL = "ONEFORALL"
ASCENSION = "ASCENSION"
FIRSTBLOOD = "FIRSTBLOOD"
KINGPORO = "KINGPORO"